# Generated by Django 2.2.16 on 2022-11-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавть картинку к публикации', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
